
name: "Pelican InElegant Build"
description: "Build a static site using Pelican InElegant"
author: "Christopher O'Brien  <obriencj@gmail.com>"


inputs:
  version:
    description: "pelican-inelegant container version"
    required: false
    default: master

  settings:
    description: "override pelican settings file"
    required: false

  content:
    description: "override content directory"
    required: false

  output:
    description: "override output directory"
    required: false

  theme:
    description: "override theme directory"
    required: false


outputs:
  settings:
    description: "Pelican configuration file"
    value: ${{ steps.settings.outputs.settings }}

  path:
    description: "Path that pelican will build from"
    value: ${{ steps.settings.outputs.path }}

  output-path:
    description: "Path that pelican will build into"
    value: ${{ steps.settings.outputs.output_path }}

  theme:
    description: "Configured THEME"
    value: ${{ steps.settings.outputs.theme }}

  site-url:
    description: "Configured SITEURL"
    value: ${{ steps.settings.outputs.siteurl }}

  site-name:
    description: "Configured SITENAME"
    value: ${{ steps.settings.outputs.sitename }}

  site-subtitle:
    description: "Configured SITESUBTITLE"
    value: ${{ steps.settings.outputs.sitesubtitle }}


runs:
  using: composite
  steps:
    - name: Record settings to output
      id: settings
      shell: bash
      run: "\
      podman run --rm --volume '${{ github.workspace }}':/work \
        --entrypoint /pelican/dump-settings.py \
        ghcr.io/obriencj/pelican-inelegant:\
          '${{ inputs.version || 'master' }}' \
        ${{ inputs.settings && format('-s''{0}''', inputs.settings) }} \
        ${{ inputs.theme && format('-t''{0}''', inputs.theme) }} \
        ${{ inputs.output && format('-o''{0}''', inputs.output) }} \
        ${{ inputs.content && format('''{0}''', inputs.content) }}
        >> $GITHUB_OUTPUT"

    - name: Build site with pelican
      shell: bash
      run: "\
      podman run --rm --volume '${{ github.workspace }}':/work \
        ghcr.io/obriencj/pelican-inelegant:\
          '${{ inputs.version || 'master' }}' \
        ${{ inputs.settings && format('-s''{0}''', inputs.settings) }} \
        ${{ inputs.theme && format('-t''{0}''', inputs.theme) }} \
        ${{ inputs.output && format('-o''{0}''', inputs.output) }} \
        ${{ inputs.content && format('''{0}''', inputs.content) }}"


# The end.
