
name: "Pelican InElegant Build"
description: "Build a static site using Pelican InElegant"
author: "Christopher O'Brien  <obriencj@gmail.com>"


inputs:
  version:
    description: "pelican-inelegant container version"
    required: false
    default: master

  settings:
    description: "override pelican settings file"
    required: false

  content:
    description: "override content directory"
    required: false

  output:
    description: "override output directory"
    required: false

  theme:
    description: "override theme directory"
    required: false


runs:
  using: composite
  steps:
    - name: Launch pelican-inelegant container
      shell: bash
      run: |
        podman run --rm --volume "${{ github.workspace }}":/work \
          "ghcr.io/obriencj/pelican-inelegant:\
           ${{ inputs.version || 'master' }}" \
          ${{ inputs.settings && format('-s''{0}''', inputs.settings) }} \
          ${{ inputs.theme && format('-t''{0}''', inputs.theme) }} \
          ${{ inputs.output && format('-o''{0}''', inputs.output }} \
          ${{ inputs.content && format('''{0}''', inputs.content) }}


# The end.
