
name: "Pelican InElegant Build"
description: "Build a static site using Pelican InElegant"
author: "Christopher O'Brien  <obriencj@gmail.com>"


inputs:
  version:
    description: "pelican-inelegant container version"
    required: false
    default: master

  settings:
    description: "override pelican settings file"
    required: false

  path:
    description: "override source content directory"
    required: false

  output-path:
    description: "override output directory"
    required: false

  theme:
    description: "override theme"
    required: false


outputs:
  settings:
    description: "Pelican configuration file"
    value: ${{ steps.settings.outputs.SETTINGS }}

  path:
    description: "Path that pelican will build from"
    value: ${{ steps.settings.outputs.PATH }}

  output-path:
    description: "Path that pelican will build into"
    value: ${{ steps.settings.outputs.OUTPUT_PATH }}

  theme:
    description: "Configured THEME"
    value: ${{ steps.settings.outputs.THEME }}

  site-url:
    description: "Configured SITEURL"
    value: ${{ steps.settings.outputs.SITEURL }}

  site-name:
    description: "Configured SITENAME"
    value: ${{ steps.settings.outputs.SITENAME }}

  site-subtitle:
    description: "Configured SITESUBTITLE"
    value: ${{ steps.settings.outputs.SITESUBTITLE }}


runs:
  using: composite
  steps:
    - name: Pull pelican-inelegant image
      shell: bash
      run: "\
      podman pull ghcr.io/obriencj/pelican-inelegant\
        '${{ inputs.version && format(':{0}', inputs.version) }}'"

    - name: Tag pelican-inelegant image
      shell: bash
      run: "\
      podman tag ghcr.io/obriencj/pelican-inelegant\
        '${{ inputs.version && format(':{0}', inputs.version) }}' \
        pelican-inelegant"

    - name: Record settings
      id: settings
      shell: bash
      run: "\
      podman run --rm --volume '${{ github.workspace }}':/work \
        --entrypoint /pelican/dump-settings.py \
        pelican-inelegant
        ${{ inputs.settings && format('-s''{0}''', inputs.settings) }} \
        ${{ inputs.theme && format('-t''{0}''', inputs.theme) }} \
        ${{ inputs.output-path && format('-o''{0}''', inputs.output-path) }} \
        ${{ inputs.path && format('''{0}''', inputs.path) }}
        >> $GITHUB_OUTPUT"

    - name: Build site with pelican
      shell: bash
      run: "\
      podman run --rm --volume '${{ github.workspace }}':/work \
        pelican-inelegant
        ${{ inputs.settings && format('-s''{0}''', inputs.settings) }} \
        ${{ inputs.theme && format('-t''{0}''', inputs.theme) }} \
        ${{ inputs.output-path && format('-o''{0}''', inputs.output-path) }} \
        ${{ inputs.path && format('''{0}''', inputs.path) }}"


# The end.
