name: Build pelican container


on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Containerfile
      - static/**
      - source/**
      - templates/**
      - entrypoint.py
      - gulpfile.babel.js
      - package.json
      - requirements.txt
      - yarn.lock
    tags:
      - v*


env:
  image: ghcr.io/${{ github.repository }}
  cache: ghcr.io/${{ github.repository }}-cache


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Log in to ghcr.io
      #   uses: redhat-actions/podman-login@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.image }}
          layers: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          containerfiles: |
            Containerfile

          # The current version of buildah is too low, and doesn't
          # actually support this kind of caching yet.

          # extra-args: |
          #   --cache-from=${{ env.cache }}
          #   --cache-to=${{ env.cache }}

      - name: Publish image
        id: publish
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust

      - name: Results
        run: |
          echo "${{ toJSON(steps.publish.outputs) }}"


# The end.
