name: Build pelican container


on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Containerfile
      - static/**
      - templates/**
    tags:
      - v*


env:
  image: pelican-inelegant
  registry: ghcr.io/${{ github.repository_owner }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Clean tags
        id: clean
        run: |
          echo tags=${{ steps.meta.outputs.tags }} | \
            sed 's,${{ env.image }}\:,,g' >> "$GITHUB_OUTPUT"

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          layers: false
          image: ${{ env.image }}
          tags: ${{ steps.clean.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true
          containerfiles: |
            Containerfile

      - name: Publish image
        id: publish
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust

      - name: Results
        run: |
          echo "${{ toJSON(steps.publish.outputs) }}"


# The end.
