name: Remove untagged images


on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 */10 * *"


env:
  package: pelican-inelegant


jobs:
  remove-package-versions:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Remove untagged
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ github.token }}
          package_name: ${{ env.package }}
          owner_type: user
          untagged_only: true
          except_untagged_multiplatform: true


# The end.
